import os
import threading
from flask import render_template, current_app
from flask_mail import Message
# from app import mail  # Moved to local imports to avoid circular dependency
from fpdf import FPDF
from io import BytesIO

def send_async_email(app, msg):
    from . import mail # Local import
    with app.app_context():
        try:
            mail.send(msg)
        except Exception as e:
            print(f"Failed to send email: {e}")
            print(f"--- MOCK EMAIL ---\nTo: {msg.recipients}\nSubject: {msg.subject}\nBody: {msg.body}\n------------------")

def send_email(subject, recipient, template=None, body=None, pdf_bytes=None, pdf_name=None):
    app = current_app._get_current_object()
    msg = Message(subject, recipients=[recipient])
    
    if body:
        msg.body = body
    if template:
        msg.html = template

    if pdf_bytes and pdf_name:
        msg.attach(pdf_name, "application/pdf", pdf_bytes)

    # Threading for non-blocking email sending
    thr = threading.Thread(target=send_async_email, args=(app, msg))
    thr.start()

def generate_pdf(data):
    """
    Generates a professional PDF report using FPDF2 (pure Python).
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)

    # Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 20, "Building Cost Estimate", ln=True, align="C")
    pdf.ln(10)

    # Header Info
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(0, 0, 0)
    pdf.write_html(f"<b>Date:</b> {data['date']}<br>")
    pdf.write_html(f"<b>Estimator ID:</b> #{data['id']}<br>")
    pdf.write_html(f"<b>Client:</b> {data['user']['name']} ({data['user']['email']})<br>")
    pdf.ln(10)

    # Project Specifications Table
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Project Specifications", ln=True)
    pdf.set_font("Helvetica", size=10)
    
    with pdf.table(col_widths=(60, 120), line_height=7) as table:
        row = table.row()
        row.cell("City")
        row.cell(data['inputs'].get('city', 'N/A'))
        row = table.row()
        row.cell("Quality")
        row.cell(data['inputs'].get('quality', 'N/A'))
        row = table.row()
        row.cell("Floors")
        row.cell(str(data['inputs'].get('floors', 'N/A')))
        row = table.row()
        row.cell("Area (sqft)")
        row.cell(str(data['inputs'].get('area_sqft_estimate', 'N/A')))
    
    pdf.ln(10)

    # Material Breakdown Table
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Material Breakdown", ln=True)
    pdf.set_font("Helvetica", size=10)
    
    bill_data = [("Material", "Quantity", "Estimated Cost (INR)")]
    key_map = {'bricks': 'Bricks', 'cement': 'Cement', 'steel': 'Steel', 'paint': 'Paint', 'labor': 'Labor'}
    
    with pdf.table(col_widths=(60, 60, 60), line_height=8, text_align="CENTER") as table:
        # Header
        row = table.row()
        for cell in bill_data[0]:
            row.cell(cell)
            
        for k, cost in data['breakdown'].items():
            name = key_map.get(k, k.capitalize())
            qty_val = "-"
            if k == 'bricks': qty_val = f"{data['quantities'].get('bricks_count', 0):,.0f} Units"
            elif k == 'cement': qty_val = f"{data['quantities'].get('cement_bags', 0):,.0f} Bags"
            elif k == 'steel': qty_val = f"{data['quantities'].get('steel_kg', 0):,.0f} Kg"
            elif k == 'paint': qty_val = f"{data['quantities'].get('paint_liters', 0):,.0f} L"
            elif k == 'labor': qty_val = f"{data['quantities'].get('worker_days', 0):,.0f} Days"
            
            row = table.row()
            row.cell(name)
            row.cell(qty_val)
            row.cell(f"Rs. {cost:,.2f}")
            
        # Total
        row = table.row()
        row.cell("TOTAL ESTIMATE", colspan=2)
        row.cell(f"Rs. {data['total']:,.2f}")

    pdf.ln(10)

    # Future Prediction
    if data.get('predicted_2026'):
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Future Price Forecast (2026)", ln=True)
        pdf.set_font("Helvetica", size=10)
        pred_text = f"Based on current market trends and inflation analysis, the estimated cost for this project in 2026 is approximately <b>Rs. {data['predicted_2026']:,.2f}</b>."
        pdf.write_html(pred_text)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 10, "Generated by Civil Estimator AI", align="C")

    # Output to BytesIO
    buffer = BytesIO()
    pdf_output = pdf.output()
    buffer.write(pdf_output)
    buffer.seek(0)
    return buffer.getvalue()
